# Generated by Django 5.2.8 on 2025-11-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('brief', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Not Started', max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('aircraft', models.CharField(blank=True, max_length=120)),
                ('no_meetings', models.PositiveIntegerField(default=0)),
                ('iom_tm', models.PositiveIntegerField(default=0)),
                ('no_sorties', models.PositiveIntegerField(default=0)),
                ('trials', models.PositiveIntegerField(default=0)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
