# Generated by Django 5.2.8 on 2026-01-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_docs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='marked_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='marked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='miscellaneous_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
